[package]
name = "vex-sdk-sys"
description = "FFI bindings to libraries compatible with the VEX runtime SDK."
repository = "https://github.com/vexide/vex-sdk/"
authors = ["Tropical"]
license = "MIT"
categories = ["science::robotics", "no-std", "embedded"]
keywords = ["vex", "vex-v5", "vex-robotics", "robotics"]
version = "0.0.1"
edition = "2021"

[dependencies]
core = { package = "rustc-std-workspace-core", version = "1.0.0", optional = true }
compiler_builtins = { version = "^0.1.109", optional = true }

[features]
rustc-dep-of-std = ["core", "compiler_builtins"]

[package.metadata.docs.rs]
targets = ["armv7a-vex-v5"]